// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a summary of a permit application for admin review.
 *
 * - adminPermitReviewSummary - A function that generates a summary of a permit application.
 * - AdminPermitReviewSummaryInput - The input type for the adminPermitReviewSummary function.
 * - AdminPermitReviewSummaryOutput - The return type for the adminPermitReviewSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AdminPermitReviewSummaryInputSchema = z.object({
  applicationDetails: z.string().describe('Details of the permit application.'),
  userInformation: z.string().describe('Information about the user submitting the application.'),
});
export type AdminPermitReviewSummaryInput = z.infer<typeof AdminPermitReviewSummaryInputSchema>;

const AdminPermitReviewSummaryOutputSchema = z.object({
  summary: z.string().describe('A summary of the permit application highlighting key information and potential issues.'),
});
export type AdminPermitReviewSummaryOutput = z.infer<typeof AdminPermitReviewSummaryOutputSchema>;

export async function adminPermitReviewSummary(input: AdminPermitReviewSummaryInput): Promise<AdminPermitReviewSummaryOutput> {
  return adminPermitReviewSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adminPermitReviewSummaryPrompt',
  input: {schema: AdminPermitReviewSummaryInputSchema},
  output: {schema: AdminPermitReviewSummaryOutputSchema},
  prompt: `You are an administrative assistant reviewing permit applications.

  Summarize the following permit application, highlighting key information and potential issues for an administrator to review.

  Application Details: {{{applicationDetails}}}
  User Information: {{{userInformation}}}
  `,
});

const adminPermitReviewSummaryFlow = ai.defineFlow(
  {
    name: 'adminPermitReviewSummaryFlow',
    inputSchema: AdminPermitReviewSummaryInputSchema,
    outputSchema: AdminPermitReviewSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
